name: firebasetask
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.0
  flutter_screenutil: ^5.0.1
  flutter_svg: ^1.0.0
  shared_preferences: ^2.0.13
  shimmer: ^2.0.0

  #dependecy injection
  get_it: ^7.2.0

  #state management
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1

  #firebase
  firebase_auth: ^3.3.7
  cloud_firestore: ^3.1.8
  firebase_core: ^1.12.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: SF Pro
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Light.otf
          weight: 300
        - asset: assets/fonts/SF-Pro-Text-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Text-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Text-Semibold.otf
          weight: 600
        - asset: assets/fonts/SF-Pro-Text-Bold.otf
          weight: 700
